//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucTap_ThuongMaiDienTu.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThucTap_ThuongMaiDienTu.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts Management.
        /// </summary>
        public static string AccountsM {
            get {
                return ResourceManager.GetString("AccountsM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string AccountsN {
            get {
                return ResourceManager.GetString("AccountsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Home.
        /// </summary>
        public static string AdminHome {
            get {
                return ResourceManager.GetString("AdminHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders.
        /// </summary>
        public static string AllOrders {
            get {
                return ResourceManager.GetString("AllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best medicines.
        /// </summary>
        public static string BestMed1 {
            get {
                return ResourceManager.GetString("BestMed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at our Institute.
        /// </summary>
        public static string BestMed2 {
            get {
                return ResourceManager.GetString("BestMed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string BestMed3 {
            get {
                return ResourceManager.GetString("BestMed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories Editor.
        /// </summary>
        public static string CategoriesE {
            get {
                return ResourceManager.GetString("CategoriesE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories Management.
        /// </summary>
        public static string CategoriesM {
            get {
                return ResourceManager.GetString("CategoriesM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Category.
        /// </summary>
        public static string CategoriesN {
            get {
                return ResourceManager.GetString("CategoriesN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string CFPassword {
            get {
                return ResourceManager.GetString("CFPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete Category:.
        /// </summary>
        public static string DeleteCategories {
            get {
                return ResourceManager.GetString("DeleteCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete User: .
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of Category:.
        /// </summary>
        public static string DetailsOfCategories {
            get {
                return ResourceManager.GetString("DetailsOfCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail of User: .
        /// </summary>
        public static string DetailsOfUser {
            get {
                return ResourceManager.GetString("DetailsOfUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to satisfied customers.
        /// </summary>
        public static string fact1 {
            get {
                return ResourceManager.GetString("fact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quality of service.
        /// </summary>
        public static string fact2 {
            get {
                return ResourceManager.GetString("fact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quality certificates.
        /// </summary>
        public static string fact3 {
            get {
                return ResourceManager.GetString("fact3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Products.
        /// </summary>
        public static string fact4 {
            get {
                return ResourceManager.GetString("fact4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping.
        /// </summary>
        public static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Payment.
        /// </summary>
        public static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Day Return.
        /// </summary>
        public static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 Support.
        /// </summary>
        public static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% No harmful chemistry.
        /// </summary>
        public static string Hero1 {
            get {
                return ResourceManager.GetString("Hero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines &amp; Dietary Supplements.
        /// </summary>
        public static string Hero2 {
            get {
                return ResourceManager.GetString("Hero2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional Medicine Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingredient.
        /// </summary>
        public static string Ingredient {
            get {
                return ResourceManager.GetString("Ingredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already got an account ?.
        /// </summary>
        public static string LoginAsk1 {
            get {
                return ResourceManager.GetString("LoginAsk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in here!.
        /// </summary>
        public static string LoginAsk2 {
            get {
                return ResourceManager.GetString("LoginAsk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Logup {
            get {
                return ResourceManager.GetString("Logup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string LogupAsk1 {
            get {
                return ResourceManager.GetString("LogupAsk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up here!.
        /// </summary>
        public static string LogupAsk2 {
            get {
                return ResourceManager.GetString("LogupAsk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines.
        /// </summary>
        public static string Medicines {
            get {
                return ResourceManager.GetString("Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines Management.
        /// </summary>
        public static string MedicinesM {
            get {
                return ResourceManager.GetString("MedicinesM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Medicine.
        /// </summary>
        public static string MedicinesN {
            get {
                return ResourceManager.GetString("MedicinesN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not logged in yet. Sign in here.
        /// </summary>
        public static string Notilogin {
            get {
                return ResourceManager.GetString("Notilogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Orders.
        /// </summary>
        public static string OrderList {
            get {
                return ResourceManager.GetString("OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Management.
        /// </summary>
        public static string OrdersM {
            get {
                return ResourceManager.GetString("OrdersM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack.
        /// </summary>
        public static string Pack {
            get {
                return ResourceManager.GetString("Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Orders.
        /// </summary>
        public static string PendingOrders {
            get {
                return ResourceManager.GetString("PendingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by keyword.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search now!.
        /// </summary>
        public static string SearchNow {
            get {
                return ResourceManager.GetString("SearchNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Orders.
        /// </summary>
        public static string ShippingOrders {
            get {
                return ResourceManager.GetString("ShippingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        public static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free on order over $300.
        /// </summary>
        public static string SubFeature1 {
            get {
                return ResourceManager.GetString("SubFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% security payment.
        /// </summary>
        public static string SubFeature2 {
            get {
                return ResourceManager.GetString("SubFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 day money guarantee.
        /// </summary>
        public static string SubFeature3 {
            get {
                return ResourceManager.GetString("SubFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support every time fast.
        /// </summary>
        public static string SubFeature4 {
            get {
                return ResourceManager.GetString("SubFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Client Saying!.
        /// </summary>
        public static string SubTesti {
            get {
                return ResourceManager.GetString("SubTesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Testimonial.
        /// </summary>
        public static string Testi {
            get {
                return ResourceManager.GetString("Testi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses.
        /// </summary>
        public static string Uses {
            get {
                return ResourceManager.GetString("Uses", resourceCulture);
            }
        }
    }
}
